URL="https://iso.pop-os.org/24.04/amd64/intel/10/pop-os_24.04_amd64_intel_10.iso"
TYPE=file
CONTENTS="\
casper_pop-os_24.04_*/filesystem.squashfs|filesystem.squashfs
casper_pop-os_24.04_*/initrd.gz|initrd
casper_pop-os_24.04_*/vmlinuz.efi|vmlinuz"
EXTRACT_INITRD="true"
INITRD_NAME="initrd"
INITRD_TYPE="zstd"
